(cl:defpackage ros_srv-srv
  (:use )
  (:export
   "IMUSWITCH"
   "<IMUSWITCH-REQUEST>"
   "IMUSWITCH-REQUEST"
   "<IMUSWITCH-RESPONSE>"
   "IMUSWITCH-RESPONSE"
   "VELODYNESWITCH"
   "<VELODYNESWITCH-REQUEST>"
   "VELODYNESWITCH-REQUEST"
   "<VELODYNESWITCH-RESPONSE>"
   "VELODYNESWITCH-RESPONSE"
  ))

