// Generated by gencpp from file ros_srv/ImuSwitch.msg
// DO NOT EDIT!


#ifndef ROS_SRV_MESSAGE_IMUSWITCH_H
#define ROS_SRV_MESSAGE_IMUSWITCH_H

#include <ros/service_traits.h>


#include <ros_srv/ImuSwitchRequest.h>
#include <ros_srv/ImuSwitchResponse.h>


namespace ros_srv
{

struct ImuSwitch
{

typedef ImuSwitchRequest Request;
typedef ImuSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ImuSwitch
} // namespace ros_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_srv::ImuSwitch > {
  static const char* value()
  {
    return "0f0513142f201da5c030b442ad26bf2d";
  }

  static const char* value(const ::ros_srv::ImuSwitch&) { return value(); }
};

template<>
struct DataType< ::ros_srv::ImuSwitch > {
  static const char* value()
  {
    return "ros_srv/ImuSwitch";
  }

  static const char* value(const ::ros_srv::ImuSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::ros_srv::ImuSwitchRequest> should match
// service_traits::MD5Sum< ::ros_srv::ImuSwitch >
template<>
struct MD5Sum< ::ros_srv::ImuSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_srv::ImuSwitch >::value();
  }
  static const char* value(const ::ros_srv::ImuSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_srv::ImuSwitchRequest> should match
// service_traits::DataType< ::ros_srv::ImuSwitch >
template<>
struct DataType< ::ros_srv::ImuSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::ros_srv::ImuSwitch >::value();
  }
  static const char* value(const ::ros_srv::ImuSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_srv::ImuSwitchResponse> should match
// service_traits::MD5Sum< ::ros_srv::ImuSwitch >
template<>
struct MD5Sum< ::ros_srv::ImuSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_srv::ImuSwitch >::value();
  }
  static const char* value(const ::ros_srv::ImuSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_srv::ImuSwitchResponse> should match
// service_traits::DataType< ::ros_srv::ImuSwitch >
template<>
struct DataType< ::ros_srv::ImuSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::ros_srv::ImuSwitch >::value();
  }
  static const char* value(const ::ros_srv::ImuSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SRV_MESSAGE_IMUSWITCH_H
