// Generated by gencpp from file ros_srv/VelodyneSwitch.msg
// DO NOT EDIT!


#ifndef ROS_SRV_MESSAGE_VELODYNESWITCH_H
#define ROS_SRV_MESSAGE_VELODYNESWITCH_H

#include <ros/service_traits.h>


#include <ros_srv/VelodyneSwitchRequest.h>
#include <ros_srv/VelodyneSwitchResponse.h>


namespace ros_srv
{

struct VelodyneSwitch
{

typedef VelodyneSwitchRequest Request;
typedef VelodyneSwitchResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VelodyneSwitch
} // namespace ros_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_srv::VelodyneSwitch > {
  static const char* value()
  {
    return "0f0513142f201da5c030b442ad26bf2d";
  }

  static const char* value(const ::ros_srv::VelodyneSwitch&) { return value(); }
};

template<>
struct DataType< ::ros_srv::VelodyneSwitch > {
  static const char* value()
  {
    return "ros_srv/VelodyneSwitch";
  }

  static const char* value(const ::ros_srv::VelodyneSwitch&) { return value(); }
};


// service_traits::MD5Sum< ::ros_srv::VelodyneSwitchRequest> should match
// service_traits::MD5Sum< ::ros_srv::VelodyneSwitch >
template<>
struct MD5Sum< ::ros_srv::VelodyneSwitchRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_srv::VelodyneSwitch >::value();
  }
  static const char* value(const ::ros_srv::VelodyneSwitchRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_srv::VelodyneSwitchRequest> should match
// service_traits::DataType< ::ros_srv::VelodyneSwitch >
template<>
struct DataType< ::ros_srv::VelodyneSwitchRequest>
{
  static const char* value()
  {
    return DataType< ::ros_srv::VelodyneSwitch >::value();
  }
  static const char* value(const ::ros_srv::VelodyneSwitchRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_srv::VelodyneSwitchResponse> should match
// service_traits::MD5Sum< ::ros_srv::VelodyneSwitch >
template<>
struct MD5Sum< ::ros_srv::VelodyneSwitchResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_srv::VelodyneSwitch >::value();
  }
  static const char* value(const ::ros_srv::VelodyneSwitchResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_srv::VelodyneSwitchResponse> should match
// service_traits::DataType< ::ros_srv::VelodyneSwitch >
template<>
struct DataType< ::ros_srv::VelodyneSwitchResponse>
{
  static const char* value()
  {
    return DataType< ::ros_srv::VelodyneSwitch >::value();
  }
  static const char* value(const ::ros_srv::VelodyneSwitchResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_SRV_MESSAGE_VELODYNESWITCH_H
